#!/usr/bin/python3

import sys
import yaml

types = {}

with open(sys.argv[1]) as f:
	lines = f.readlines()
	f.close()
	for l in lines:
		c = l.split()
		types[c[0]] = {}
		types[c[0]]["cpu"] = c[1]
		types[c[0]]["mem"] = c[2]
print(yaml.dump(types, default_flow_style=False))
